
// AUTH ACTIONS
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCESSS = 'LOGOUT_SUCESSS';
export const USER_LOADED = 'USER_LOADED';
export const FAILED_AUTH_CHECK = 'FAILED_AUTH_CHECK';



// BLOG ACTIONS
export const FETCH_BLOG_REQUEST = "FETCH_BLOG_REQUEST";
export const FETCH_BLOG_SUCCESS = "FETCH_BLOG_SUCCESS";
export const FETCH_BLOG_FAILURE = "FETCH_BLOG_FAILURE";

// USER MANAGE ACTIONS
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS ="ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS ="DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS ="UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

// EDITOR TYPES 
export const EDITOR_FETCH_BLOG_REQUEST = "EDITOR_FETCH_BLOG_REQUEST";
export const EDITOR_FETCH_BLOG_SUCCESS = "EDITOR_FETCH_BLOG_SUCCESS";
export const EDITOR_FETCH_BLOG_FAILURE = "EDITOR_FETCH_BLOG_FAILURE";

export const EDITOR_FETCH_IMAGES_SUCCUESS ="EDITOR_FETCH_IMAGES_SUCCUESS";
export const EDITOR_FETCH_IMAGES_FAILURE ="EDITOR_FETCH_IMAGES_FAILURE";
export const EDITOR_FETCH_IMAGES_REQUEST = "EDITOR_FETCH_IMAGES_REQUEST";

export const EDITOR_SAVE_IMAGES_SUCCUESS ="EDITOR_SAVE_IMAGES_SUCCUESS";
export const EDITOR_SAVE_IMAGES_FAILURE ="EDITOR_SAVE_IMAGES_FAILURE";
export const EDITOR_SAVE_IMAGES_REQUEST = "EDITOR_SAVE_IMAGES_REQUEST";

export const EDITOR_SAVE_SUCCESS = "EDITOR_SAVE_SUCCESS";
export const EDITOR_SAVE_FAIL = "EDITOR_SAVE_SUCCESS";
export const EDITOR_SAVE_ERROR_CLEAR = "EDITOR_SAVE_ERROR_CLEAR";
export const SELECT_BLOG = "SELECT_BLOG";
export const UPDATE_EDITOR_BLOG = "UPDATE_NEW_BLOG";
export const SAVE_EDITOR_BLOG = "SAVE_NEW_BLOG";
export const CLOSE_EDITOR_BLOG = "CLOSE_NEW_BLOG";
export const OPEN_NEW_BLOG = "OPEN_NEW_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const TOGGLE_PREVIEW = "TOGGLE_PREVIEW"


