export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCESSS = 'LOGOUT_SUCESSS';
export const USER_LOADED = 'USER_LOADED';
export const FAILED_AUTH_CHECK = 'FAILED_AUTH_CHECK';




export const FETCH_BLOG_REQUEST = "FETCH_BLOG_REQUEST";
export const FETCH_BLOG_SUCCESS = "FETCH_BLOG_SUCCESS";
export const FETCH_BLOG_FAILURE = "FETCH_BLOG_FAILURE";


// EDITOR TYPES 
export const EDITOR_FETCH_BLOG_REQUEST = "EDITOR_FETCH_BLOG_REQUEST";
export const EDITOR_FETCH_BLOG_SUCCESS = "EDITOR_FETCH_BLOG_SUCCESS";
export const EDITOR_FETCH_BLOG_FAILURE = "EDITOR_FETCH_BLOG_FAILURE";
export const EDITOR_SAVE_SUCCESS = "EDITOR_SAVE_SUCCESS";
export const EDITOR_SAVE_FAIL = "EDITOR_SAVE_SUCCESS";
export const EDITOR_SAVE_ERROR_CLEAR = "EDITOR_SAVE_ERROR_CLEAR";
export const SELECT_BLOG = "SELECT_BLOG";
export const UPDATE_EDITOR_BLOG = "UPDATE_NEW_BLOG";
export const SAVE_EDITOR_BLOG = "SAVE_NEW_BLOG";
export const CLOSE_EDITOR_BLOG = "CLOSE_NEW_BLOG";
export const OPEN_NEW_BLOG = "OPEN_NEW_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const TOGGLE_PREVIEW = "TOGGLE_PREVIEW"


